### ISSUE TITLE
DOCS/WIKI

### ISSUE THREAD

**Issue by illyrius666** [XodiumSoftware/xCAD#193]
### Description:
The DOCS/WIKI is not complete and functioning.
`.github/workflows/sten_ci_cd.yml`

### Tasks:
- [x] Task 1: Analyze the problems.
- [x] Task 2: Come up with a solution to the problems.
- [ ] Task 3: Solve the problems.

### Expected Outcome:
- Fully functioning pdoc setup that takes the codebase and transforms it into a "wiki".

### Additional Information:
- PDoc how-to documentation

### Related Issues:
- #192
