### ISSUE TITLE
StenLib Logger

### ISSUE THREAD

**Issue by illyrius666** [XodiumSoftware/xCAD#196]
### Description:
The Logger class in StenLib needs to be refactored since alot of features are hardcoded.
`StenLib/logger.py`

### Tasks:
- [x] Task 1: Analyze the problems.
- [x] Task 2: Come up with a solution to the problems.
- [x] Task 3: Solve the problems.

### Expected Outcome:
- Refactor to remove hardcoded parts, optimize and add propper docstrings.

### Additional Information:
- Python how-to documentation

### Related Issues:
- None
