### ISSUE TITLE
StenLib Tests

### ISSUE THREAD

**Issue by illyrius666** [XodiumSoftware/xCAD#199]
### Description:
Create unittests for StenLib.
`StenLib/tests`

### Tasks:
- [x] Task 1: Analyze the problems.
- [x] Task 2: Come up with a solution to the problems.
- [ ] Task 3: Solve the problems.

### Expected Outcome:
- Fully functional testcase.

### Additional Information:
- Unittest how-to documentation

### Related Issues:
- None
