### ISSUE TITLE
Move wiki to website

### ISSUE THREAD

**Issue by illyrius666** [XodiumSoftware/xCAD#201]
### Description:
Move wiki to the website.
`wiki.structura-engineering.com`

### Tasks:
- [x] Task 1: Analyze the problems.
- [x] Task 2: Come up with a solution to the problems.
- [x] Task 3: Solve the problems.

### Expected Outcome:
- Moved wiki to website.

### Additional Information:
- None

### Related Issues:
- None
