### ISSUE TITLE
WIKI V2

### ISSUE THREAD

**Issue by illyrius666** [XodiumSoftware/xCAD#207]
Update the wiki to a better version of itself.

**TASKS:**
- [x] Make the 2 wikis be integrated in one.
- [x] Change its theme.
- [x] add redirects.
- [x] fix icon bug.
- [x] automate _modules files creation.
- [x] rewrite docstrings propperly.

**Comment by illyrius666** [comment]
- resizing icon didnt work.
- automate the creation of the _modules files and content.
